name: "atividade4_dbt"
version: "1.0.0"
config-version: 2

profile: "atividade4"

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:

  atividade4_dbt:

    trusted:
      +materialized: table
      +schema: trusted

    intermediate:
      +materialized: ephemeral

    delivery:
      +materialized: table
      +schema: delivery